apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: test2-container
      image: gcr.io/google-samples/node-hello:1.0
      envFrom:
        # Define the environment variable
      - configMapRef:
          name: datos-env-mysql
  restartPolicy: Never
